version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mgf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mgf_root_password_2024
      MYSQL_DATABASE: mgf_website
      MYSQL_USER: mgf_user
      MYSQL_PASSWORD: mgf_password_2024
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mgf_db_data:/var/lib/mysql
    networks:
      - mgf_network

  # PHP Apache Web Server
  web:
    build: .
    container_name: mgf_web
    restart: unless-stopped
    ports:
      - "9527:80"  # Port 9527 trên VPS -> Port 80 trong container
    volumes:
      - ./:/var/www/html
      - ./uploads:/var/www/html/uploads
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mgf_website
      - DB_USER=mgf_user
      - DB_PASS=mgf_password_2024
    networks:
      - mgf_network
      - halife_network

volumes:
  mgf_db_data:
    driver: local

networks:
  mgf_network:
    driver: bridge
  halife_network:
    external: true
    name: halife_network
